### ISSUE TITLE
Crawler da Agencia Nacional de Águas

### ISSUE THREAD

**Issue by bmentges** [bmentges/aguas_rj_bigdata#1]
# Objetivo

Automatizar a ingestão de dados vindos da Agência Nacional de Águas para todos os reservatórios do Estado do Rio de Janeiro.

# Critérios de Aceite

- [x] Script executável que recebe via parâmetro a data de início e a data de fim para crawlear
- [x] Gera os arquivos .html corretamente para cada reservatório dentro do período selecionado
- [x] Se houver falha, não afeta o download anterior

Obs:
* Não precisa limpar downloads antigos (deve ser feito de outra forma)

# Onde estão os dados?

http://sar.ana.gov.br/MedicaoSin?dropDownListEstados=20&dropDownListReservatorios=19083&dataInicial=01%2F01%2F2016&dataFinal=03%2F02%2F2018&button=Buscar

# TODO

- [x] SPIKE (pesquisar): como crawlear os dados no formato que já baixamos antes (o exportar para excel deles, que na verdade baixa HTML) para aproveitar o CSV parser. Entrega: Definir a arquitetura do crawler no README
- [x] Permitir escolher o período para crawlear (para futuros deltas)
- [x] Atualizar o CSV parser para considerar diretórios de mais períodos
- [x] Teste integrado
- [x] Merge no master
