### ISSUE TITLE
Disponibilizar as estatísticas dos principais reservatórios na Home

### ISSUE THREAD

**Issue by bmentges** [bmentges/aguas_rj_bigdata#2]
# Objetivo

Disponibilizar as estatísticas dos principais reservatórios na Home. Elegi os principais reservatórios baseado na página já abandonada do G1: http://especiais.g1.globo.com/economia/crise-da-agua/nivel-dos-reservatorios/

São eles:
- Nome | Capacidade total em bilhões de litros)
- Paraibuna | 4.732,2
- Jaguari | 1.235,6
- Funil | 888,3
- Santa Branca | 438,3

Esses reservatórios atendem 12,3 milhões de pessoas.

# Critérios de Aceite

- [x] Entrar na home e poder ver as estatísticas dos 4 principais reservatórios do RJ
- [ ] Entrar na home e saber se a média semanal de cada um é positiva ou negativa, e em quantos porcento
- [x] A interface ser um componente react com testes unitários, para posterior reuso na página dos reservatórios (onde poderemos escolher um dos 150)

# TODO:

- [x] Definir quais estatísticas mostrar
- [x] Definir em que tempo da pipeline de dados devemos plotar e gerar os gráficos (se vamos pré-gerar ou fazer on-the-fly, com argumentos aqui)
- [x] Integrar React.js
- [x] Criar componente de estatistica 
- [x] Implementar na home
- [x] Testar
- [x] Aprovar
- [x] Merge
