### ISSUE TITLE
API dos reservatórios e medições

### ISSUE THREAD

**Issue by bmentges** [bmentges/aguas_rj_bigdata#3]
# Objetivo

Poder consultar os dados de um reservatório através de uma API REST

# Critérios de Aceite

- [x] API REST de dados dos reservatórios (GET / POST / PUT / DELETE)
- [x] Dados obtidos e processados já pré-populados no banco
- [x] Cache com memcached

Obs:
- Sem autenticação no momento (autenticação da API tem sua própria issue)

# TODO

- [x] Definir arquitetura das APIs no README
- [x] Implementar API
- [x] Implementar script que carrega dados processados no banco
- [ ] ~~~Testes unitários~~~ 
- [ ] ~~~Testes integrados~~~
- [ ] ~~~Pegar aprovação~~~
- [x] Merge

**Comment by bmentges** [comment]
Implementado na tag 0.1.0.
