### ISSUE TITLE
Página do reservatório

### ISSUE THREAD

**Issue by bmentges** [bmentges/aguas_rj_bigdata#4]
# Visão Geral

Criar uma página com as informações principais de um reservatório, genérica, para mostrar suas informações e estatísticas.

A página deverá conter uma forma de buscar e selecionar o reservatório para mostrar.

Preferência para um loading único dos dados, ao invés de a cada escolha.

Detalhe: Componente ReactJS

## TODO

- [ ] Instalar o ReactJS no projeto e servir através do Django (decidir se devemos integrar)
- [ ] Especificar API de dados a serem consumidos
- [ ] Definir métricas e estatísticas a mostrar na página
- [ ] Implementar página
- [ ] Merge
